### ISSUE TITLE
Wrap content property and other doubts

### ISSUE THREAD

**Issue by omkar-tenkale** [kwameopareasiedu/react-constraint-layout#10]
In the examples and readme thee is no wrap-content property mentioned. 

Is it supported by this lib? 

Also what is default width height if not specified

Are they compulsory to specify as in android? 

In examples 
two different properties can be seen 
match-parent and match-content

Are they same or different?

**Comment by kwameopareasiedu** [comment]
**match-content** serves the same function as **wrap-content** in Android. It is not the same as **match-parent**. The default width of the Constraint layout is the width of it's parent (or the window if is a topmost element). The height was supposed to be computed from the height of the children and the constraints on them...
